apiVersion: v1
kind: Service
metadata:
  name: spring-deployment-service
  namespace: default
  labels:
    app: spring
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: spring
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: spring
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: spring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  serviceName: nginx
  template:
    metadata:
      labels:
        app: spring
    spec:
      terminationGracePeriodSeconds: 10
      updateStrategy: RollingUpdate
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: "/user/share/nginx/"
          name: pv-mongo
      - name: spring
        image: turok2step/docker_spring:0.1.2
      - name: mongo
        image: mongo:latest
        volumeMounts:
        - mountPath: "/usr/share/mongo/"
          name: pv-mongo
  volumeClaimTemplates:
    - metadata:
        name: pv-mongo
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "fast"
        resources:
          requests:
            storage: 1Gi
